import {test,expect} from '@playwright/test';
async function navigate(page:any,url:string){for(let attempt=0;attempt<5;attempt++){try{return await page.goto(url,{waitUntil:'commit',timeout:15_000})}catch(error){if(!String(error).includes('ERR_ABORTED')||attempt===4)throw error;const expected=new URL(url,page.url());if(new URL(page.url()).pathname===expected.pathname){await page.waitForLoadState('domcontentloaded').catch(()=>{});return}await page.waitForTimeout(100)}}}
async function login(page:any){await navigate(page,'/login');await page.getByLabel('E-mail').fill('alex@kurio.art');await page.getByLabel('Senha').fill('kurio123');await page.getByRole('button',{name:'Entrar'}).click();await page.waitForURL('/');}
test.beforeEach(async({page})=>{await navigate(page,'/');await page.evaluate(()=>localStorage.clear());await page.reload()});
test('catalog search, filter, sorting and pagination are reflected in the URL',async({page})=>{await expect(page.getByRole('heading',{name:'Mercado NFT'})).toBeVisible();await page.getByRole('button',{name:/Jungle Apes/}).click();await expect(page).toHaveURL(/category=Ape/);await page.getByLabel('Ordenar por').selectOption('price-asc');await expect(page).toHaveURL(/sort=price-asc/);await page.getByLabel('Buscar NFTs').fill('Night Walker');await page.getByRole('button',{name:'Pesquisar'}).click();await expect(page).toHaveURL(/q=Night/);await expect(page.getByRole('link',{name:'Night Walker #209',exact:true})).toBeVisible();await page.goBack();await expect(page).toHaveURL(/sort=price-asc/)});
test('direct NFT route and unknown NFT have useful states',async({page})=>{await navigate(page,'/nft/ape-042');await expect(page.getByRole('heading',{name:'Emerald Ape #042'})).toBeVisible();await navigate(page,'/nft/missing-asset');await expect(page.getByText('Esta edição não está disponível.')).toBeVisible()});
test('login, add artwork and complete the simulated order',async({page})=>{await navigate(page,'/login');await page.getByLabel('E-mail').fill('alex@kurio.art');await page.getByLabel('Senha').fill('kurio123');await page.getByRole('button',{name:'Entrar'}).click();await page.waitForURL('/');await navigate(page,'/nft/ape-042');await page.getByRole('button',{name:'Adicionar ao carrinho'}).click();await navigate(page,'/cart');await expect(page.getByText('Emerald Ape #042')).toBeVisible();await navigate(page,'/checkout');await page.getByRole('button',{name:'Revisar pedido'}).click();await page.getByRole('button',{name:'Confirmar compra'}).click();await expect(page.getByRole('heading',{name:'Parabéns pela sua nova coleção!'})).toBeVisible()});
test('invalid coupon returns visible feedback',async({page})=>{await navigate(page,'/cart');await page.getByLabel('Código promocional').fill('BADCODE');await page.getByRole('button',{name:'Aplicar'}).click();await expect(page.getByRole('status')).toContainText('Cupom inválido')});
test('registration reports duplicate accounts and invalid credentials',async({page})=>{await navigate(page,'/register');await page.getByLabel('Nome completo').fill('Alex Teste');await page.getByLabel('E-mail').fill('alex@kurio.art');await page.getByLabel('Senha').fill('senha-segura');await page.getByRole('button',{name:'Criar conta'}).click();await expect(page.getByRole('alert')).toContainText('já possui cadastro');await navigate(page,'/login');await page.getByLabel('E-mail').fill('alex@kurio.art');await page.getByLabel('Senha').fill('errada1');await page.getByRole('button',{name:'Entrar'}).click();await expect(page.getByRole('alert')).toContainText('inválidos')});
test('authenticated favorites toggle and remain in the account session',async({page})=>{await login(page);await page.getByRole('button',{name:'Adicionar aos favoritos'}).first().click();await expect(page.getByRole('button',{name:'Remover dos favoritos'}).first()).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Remover dos favoritos'}).first()).toBeVisible()});
test('cart quantity, coupon and cart state survive refresh and sign-in',async({page})=>{await navigate(page,'/nft/ape-042');await page.getByRole('button',{name:'Aumentar quantidade'}).click();await expect(page.locator('.buy-row .quantity span')).toHaveText('2');await page.getByRole('button',{name:'Adicionar ao carrinho'}).click();await expect(page.getByRole('status')).toContainText('Adicionado ao carrinho');await navigate(page,'/cart');await expect(page.locator('.cart-row .quantity span')).toHaveText('2');await page.getByLabel('Código promocional').fill('KURIO10');await page.getByRole('button',{name:'Aplicar'}).click();await expect(page.getByText('Desconto')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Remover',exact:true})).toBeVisible();await login(page);await navigate(page,'/cart');await expect(page.getByText('Emerald Ape #042')).toBeVisible()});
test('profile and wallet screens validate and save changes',async({page})=>{await login(page);await navigate(page,'/profile');await page.getByLabel('Nome completo').fill('Alex Ribeiro Atualizado');await page.getByRole('button',{name:'Salvar alterações'}).click();await expect(page.getByRole('status')).toContainText('Perfil atualizado');await navigate(page,'/profile/activity');await expect(page.getByRole('heading',{name:'Atividade',exact:true})).toBeVisible();await page.getByRole('link',{name:'Lista de interesse'}).click();await expect(page.getByRole('heading',{name:'Lista de interesse',exact:true})).toBeVisible();await navigate(page,'/wallets');await page.getByPlaceholder('Ex.: Minha MetaMask').fill('Rabby');await page.getByPlaceholder('Ex.: Principal').fill('Pessoal');await page.getByLabel(/Rede/).selectOption('Ethereum');await page.getByLabel(/Endereço da carteira/).fill('0xabcdef123456');await page.getByLabel(/Tipo de carteira/).selectOption('MetaMask');await page.getByLabel(/Código de indicação/).fill('KURIO');await page.getByPlaceholder('Seu nome ENS').fill('alex');await page.getByRole('button',{name:'Salvar carteira'}).click();await expect(page.getByText('Rabby')).toBeVisible()});
test('market changes arrive through the Socket.IO mock and update the detail price',async({page})=>{test.setTimeout(35_000);await navigate(page,'/nft/ape-042');await expect(page.getByText('0.89 ETH')).toBeVisible({timeout:25_000})});
test('visual baselines cover home, detail, cart and payment',async({page})=>{test.setTimeout(60_000);await navigate(page,'/');await expect(page.getByRole('heading',{name:'Mercado NFT'})).toBeVisible();await expect(page).toHaveScreenshot('home.png',{fullPage:true,animations:'disabled'});await navigate(page,'/nft/ape-042');await expect(page.getByRole('heading',{name:'Emerald Ape #042'})).toBeVisible();await expect(page).toHaveScreenshot('detail.png',{fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'Adicionar ao carrinho'}).click();await expect(page.getByRole('status')).toContainText('Adicionado ao carrinho');await navigate(page,'/cart');await expect(page.getByText('Emerald Ape #042')).toBeVisible();await expect(page).toHaveScreenshot('cart.png',{fullPage:true,animations:'disabled'});await login(page);await navigate(page,'/checkout');await expect(page.getByRole('heading',{name:'Pagamento do carrinho'})).toBeVisible();await expect(page).toHaveScreenshot('checkout.png',{fullPage:true,animations:'disabled'})});
