import { http, HttpResponse, delay } from 'msw';
import type { CartItem, NFT, Order, User, Wallet } from './types';
const artworks=[
 ['ape-042','Emerald Ape #042','0.85','Ape','/art/emerald-ape-042.jpg'],['ape-118','Violet Ape #118','1.20','Ape','/art/violet-ape-118.jpg'],['ape-209','Night Walker #209','0.72','Ape','/art/night-walker-209.jpg'],['ape-031','Golden Spirit #031','0.95','Spirit','/art/golden-spirit-031.jpg'],['ape-077','Golden Spirit #077','1.45','Spirit','/art/spirit.svg'],['ape-304','Lilac Voyager #304','0.68','Voyager','/art/voyager.svg'],['ape-151','Moss Traveler #151','1.08','Voyager','/art/voyager.svg'],['ape-501','Solar Dream #501','2.10','Spirit','/art/spirit.svg'],['ape-116','Cosmic Bloom #116','0.55','Voyager','/art/voyager.svg'],['ape-244','Jungle Echo #244','0.80','Ape','/art/ape.svg'],['ape-066','Amber Nomad #066','1.62','Spirit','/art/spirit.svg'],['ape-337','Quiet Orbit #337','0.74','Voyager','/art/voyager.svg']
] as const;
const artworkByFamily:Record<string,string>={'Emerald Ape':'/art/emerald-ape-042.jpg','Violet Ape':'/art/violet-ape-118.jpg','Night Walker':'/art/night-walker-209.jpg','Golden Spirit':'/art/golden-spirit-031.jpg'};
const suppliedNFTImages=Object.values(artworkByFamily);
const randomArtFamilies=new Set(['Moss Traveler','Solar Dream','Cosmic Bloom','Jungle Echo','Amber Nomad','Quiet Orbit','Lilac Voyager']);
const familyHash=(family:string)=>Array.from(family).reduce((hash,char)=>Math.imul(hash^char.charCodeAt(0),16777619),2166136261)>>>0;
const artworkFor=(name:string,fallback:string)=>{const family=name.replace(/\s+#\d+.*$/,'').trim();if(artworkByFamily[family])return artworkByFamily[family];if(randomArtFamilies.has(family))return suppliedNFTImages[familyHash(family)%suppliedNFTImages.length];return fallback};
const persist=<T,>(k:string,initial:T):T=>{try{return JSON.parse(localStorage.getItem('kurio:'+k)||'null')??initial}catch{return initial}};
const marketUpdates=persist<Record<string,Partial<NFT>>>('market',{});
export const catalog:NFT[]=artworks.map((a,i)=>({id:a[0],name:a[1],creator:['Kurio Studio','Nina Costa','Studio Nômade'][i%3],collection:'Diário da Selva',price:a[2],supply:[2,5,1,4,3,6,2,1,8,3,2,7][i],image:artworkFor(a[1],a[4]),category:a[3],network:'Ethereum',description:'Uma peça original da coleção Diário da Selva. Cada personagem retrata um fragmento de um universo digital criado à mão.',version:1,...marketUpdates[a[0]]}));
let accounts:User[]=persist('accounts',[{id:'u1',name:'Alex Ribeiro',email:'alex@kurio.art',avatar:'/art/avatar.svg'},{id:'u2',name:'Marina Alves',email:'marina@kurio.art',avatar:'/art/avatar.svg'}]);
const hashSecret=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(byte=>byte.toString(16).padStart(2,'0')).join('');
let credentials:Record<string,string>=persist('credentials',{'alex@kurio.art':'f1299649dde49895c6ee4947b435590f8502462ebeeee8cffc01895cd2c5280e','marina@kurio.art':'f1299649dde49895c6ee4947b435590f8502462ebeeee8cffc01895cd2c5280e'});
let user:User|null=persist('user',null), cart:CartItem[]=persist('cart',[]), favorites:string[]=persist('favorites',[]), profile:Record<string,string>=persist('profile',{}), wallets:Wallet[]=persist('wallets',[{id:'w1',name:'MetaMask',address:'0x71C...9A42',network:'Ethereum',primary:true}]), orders:Order[]=persist('orders',[]), orderSignatures:Record<string,string>=persist('orderSignatures',{});
const save=()=>{localStorage.setItem('kurio:user',JSON.stringify(user));localStorage.setItem('kurio:accounts',JSON.stringify(accounts));localStorage.setItem('kurio:credentials',JSON.stringify(credentials));localStorage.setItem('kurio:cart',JSON.stringify(cart));localStorage.setItem('kurio:favorites',JSON.stringify(favorites));localStorage.setItem('kurio:profile',JSON.stringify(profile));localStorage.setItem('kurio:wallets',JSON.stringify(wallets));localStorage.setItem('kurio:orders',JSON.stringify(orders));localStorage.setItem('kurio:orderSignatures',JSON.stringify(orderSignatures))};
const scale=10000n;const units=(value:string|number)=>{const [whole='',fraction='']=String(value).split('.');return BigInt(whole||'0')*scale+BigInt((fraction+'0000').slice(0,4))};const decimal=(value:bigint)=>`${value/scale}.${String(value%scale).padStart(4,'0')}`;
const auth=()=>user?null:HttpResponse.json({message:'Entre na sua conta para continuar.'},{status:401});
export const handlers=[
 http.get('/api/nfts',async({request})=>{await delay(Number(new URL(request.url).searchParams.get('latency')||300));const q=new URL(request.url).searchParams;let items=[...catalog];const search=(q.get('q')||'').toLowerCase();if(search)items=items.filter(n=>`${n.name} ${n.creator} ${n.collection}`.toLowerCase().includes(search));const category=q.get('category');if(category&&category!=='Todas')items=items.filter(n=>n.category===category);const max=Number(q.get('max')||100);items=items.filter(n=>Number(n.price)<=max);const sort=q.get('sort');if(sort==='price-asc')items.sort((a,b)=>Number(a.price)-Number(b.price));if(sort==='price-desc')items.sort((a,b)=>Number(b.price)-Number(a.price));const page=Number(q.get('page')||1),limit=6;return HttpResponse.json({items:items.slice((page-1)*limit,page*limit),total:items.length,page,limit})}),
 http.get('/api/nfts/:id',({params})=>{const nft=catalog.find(n=>n.id===params.id);return nft?HttpResponse.json(nft):HttpResponse.json({message:'Obra não encontrada.'},{status:404})}),
 http.get('/api/session',()=>HttpResponse.json({user})),
 http.post('/api/session/login',async({request})=>{const b=await request.json() as {email:string;password:string};const email=b.email.toLowerCase();const match=accounts.find(u=>u.email.toLowerCase()===email);if(!match||credentials[email]!==await hashSecret(b.password))return HttpResponse.json({message:'E-mail ou senha inválidos.'},{status:401});user=match;save();return HttpResponse.json({user})}),
 http.post('/api/session/register',async({request})=>{const b=await request.json() as {name:string;email:string;password:string};const email=b.email.toLowerCase();if(accounts.some(u=>u.email.toLowerCase()===email))return HttpResponse.json({message:'Este e-mail já possui cadastro.'},{status:409});if(b.password.length<8)return HttpResponse.json({message:'A senha precisa ter ao menos 8 caracteres.'},{status:422});user={id:`u${Date.now()}`,name:b.name,email:b.email,avatar:'/art/avatar.svg'};accounts.push(user);credentials[email]=await hashSecret(b.password);save();return HttpResponse.json({user},{status:201})}),
 http.post('/api/session/logout',()=>{user=null;save();return HttpResponse.json({ok:true})}),
 http.get('/api/favorites',()=>{const e=auth();return e||HttpResponse.json(favorites)}),
 http.post('/api/favorites/:id',({params})=>{const e=auth();if(e)return e;favorites=[...new Set([...favorites,String(params.id)])];save();return HttpResponse.json(favorites)}),
 http.delete('/api/favorites/:id',({params})=>{const e=auth();if(e)return e;favorites=favorites.filter(id=>id!==params.id);save();return HttpResponse.json(favorites)}),
 http.get('/api/cart',()=>HttpResponse.json(cart.map(c=>({item:c,nft:catalog.find(n=>n.id===c.nftId)})).filter(x=>x.nft))),
 http.post('/api/cart',async({request})=>{const b=await request.json() as CartItem;const n=catalog.find(x=>x.id===b.nftId);if(!n)return HttpResponse.json({message:'Obra indisponível.'},{status:404});const old=cart.find(x=>x.nftId===b.nftId);const next=(old?.quantity||0)+b.quantity;if(next>n.supply)return HttpResponse.json({message:`Disponíveis: ${n.supply}`},{status:409});cart=old?cart.map(x=>x.nftId===b.nftId?{...x,quantity:next}:x):[...cart,b];save();return HttpResponse.json(cart)}),
 http.patch('/api/cart/:id',async({params,request})=>{const {quantity}=await request.json() as {quantity:number};const n=catalog.find(x=>x.id===params.id);if(!n||quantity>n.supply)return HttpResponse.json({message:'Quantidade indisponível.'},{status:409});cart=cart.map(x=>x.nftId===params.id?{...x,quantity}:x);save();return HttpResponse.json(cart)}),
 http.delete('/api/cart/:id',({params})=>{cart=cart.filter(x=>x.nftId!==params.id);save();return HttpResponse.json(cart)}),
 http.post('/api/quote',async({request})=>{const b=await request.json() as {coupon?:string};if(b.coupon&&b.coupon.toUpperCase()!=='KURIO10')return HttpResponse.json({message:'Cupom inválido ou expirado.'},{status:422});const subtotal=cart.reduce((s,c)=>s+units(catalog.find(n=>n.id===c.nftId)?.price||0)*BigInt(c.quantity),0n);const discount=b.coupon?subtotal/10n:0n;const fee=subtotal*25n/1000n;return HttpResponse.json({subtotal:decimal(subtotal),discount:decimal(discount),fee:decimal(fee),total:decimal(subtotal-discount+fee),version:catalog.reduce((s,n)=>s+n.version,0)})}),
 http.post('/api/orders',async({request})=>{const e=auth();if(e)return e;const key=(request.headers.get('Idempotency-Key')||'').trim();const b=await request.json() as {coupon?:string;quoteVersion?:number};const signature=JSON.stringify({coupon:b.coupon||'',cart});const old=orders.find(o=>o.id===key);if(old)return orderSignatures[key]!==signature?HttpResponse.json({message:'Chave de idempotência reutilizada com conteúdo diferente.'},{status:409}):HttpResponse.json(old);const version=catalog.reduce((s,n)=>s+n.version,0);if(b.quoteVersion!==undefined&&b.quoteVersion!==version)return HttpResponse.json({message:'Preço ou disponibilidade mudou. Revise os valores e confirme novamente.'},{status:409});const items=cart.map(c=>({nft:catalog.find(n=>n.id===c.nftId)!,quantity:c.quantity})).filter(x=>x.nft);if(!items.length)return HttpResponse.json({message:'Carrinho vazio.'},{status:409});const subtotal=items.reduce((s,x)=>s+units(x.nft.price)*BigInt(x.quantity),0n),fee=subtotal*25n/1000n,discount=b.coupon?.toUpperCase()==='KURIO10'?subtotal/10n:0n;const status=(new URL(request.url).searchParams.get('decline')==='1'?'rejected':'confirmed') as Order['status'];const order:Order={id:key||crypto.randomUUID(),status,items,subtotal:decimal(subtotal-discount),fee:decimal(fee),total:decimal(subtotal-discount+fee),tx:'0x'+Math.random().toString(16).slice(2,14).padEnd(12,'0'),createdAt:new Date().toISOString()};orders=[order,...orders];orderSignatures[order.id]=signature;if(status==='confirmed')cart=[];save();return HttpResponse.json(order,{status:201})}),
 http.get('/api/orders/:id',({params})=>{const o=orders.find(x=>x.id===params.id);return o?HttpResponse.json(o):HttpResponse.json({message:'Pedido não encontrado.'},{status:404})}),
 http.get('/api/profile',()=>{const e=auth();return e||HttpResponse.json({...user,...profile})}),
 http.put('/api/profile',async({request})=>{const e=auth();if(e)return e;profile={...profile,...await request.json() as Record<string,string>};if(user&&profile.name)user={...user,name:profile.name};save();return HttpResponse.json({...user,...profile})}),
 http.get('/api/wallets',()=>{const e=auth();return e||HttpResponse.json(wallets)}),
 http.post('/api/wallets',async({request})=>{const e=auth();if(e)return e;const b=await request.json() as Omit<Wallet,'id'>;wallets=[...wallets,{...b,id:crypto.randomUUID()}];save();return HttpResponse.json(wallets,{status:201})}),
 http.put('/api/wallets/:id',async({params,request})=>{const e=auth();if(e)return e;const patch=await request.json() as Partial<Wallet>;wallets=wallets.map(w=>w.id===params.id?{...w,...patch}:w);save();return HttpResponse.json(wallets)})
];
export function updateMarketPrice(id:string,price:string,supply:number){const n=catalog.find(x=>x.id===id);if(n){n.price=price;n.supply=supply;n.version++;marketUpdates[id]={price,supply,version:n.version};localStorage.setItem('kurio:market',JSON.stringify(marketUpdates));}}
